//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weatherApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string address1 { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string telephoneNo { get; set; }
        public string empRole { get; set; }
        public string email { get; set; }
        public string addressLocation { get; set; }
    }
}
